### ISSUE TITLE
Exportar aquivo de configuração de ambientes

### ISSUE THREAD

**Issue by EndreoTodimo** [totvs/tds-monitor-frontend#15]
Legal se houver possibilidade de exportar arquivo de configuração e importar para outra maquina sendo necessário só incluir usuário e senha.

**Comment by danielbolognani** [comment]
Olá, primeiramente desculpe pela demora na resposta.
Agradecemos a sugestão, mas não é algo que temos no nosso roadmap. 
Pelo produto ter o código aberto, a sua evolução também é colaborativa, portanto se quiser pode também nos enviar um Pull Request com essa melhoria que analisamos.
