### ISSUE TITLE
Porque a coluna com a cTreeTskId chama "RPO" ?

### ISSUE THREAD

**Issue by bardez** [totvs/tds-monitor-frontend#3]
Boa tarde @rogeriorc , conversando com o pessoal por aqui, não relacionamos a coluna "cTreeTskId" chama "RPO" .

Apenas por curiosidade e entendimento dos dados do monitor.

Obrigado desde já

**Comment by rogeriorc** [comment]
Boa tarde @bardez ,

Não sei te dizer, peguei do projeto do Monitor VsCode Plugin (https://github.com/totvs/tds-monitor)

@brodao , saberia nos dizer?

**Comment by brodao** [comment]
Senhores,

Suspeito que pode esta ocorrendo:
1. Titulo da coluna errada, p.e. tradução ou erro mesmo de "digitação".
OU
2.O mesmo monitor é utilizado para diversas versões de servidor e há
diferenças na quantidade de colunas.
Pode ter ocorrido deslocamento.

[:>} Alan Cândido ><>


*Especialista de Pesquisa e DesenvolvimentoExpert Research and Development*
.[====].[====].(----).(----).\___/.[___].]@|--Y\_
 _o__o___o__o___o__o___o__o___o_o___o_o___O___oo_\


Em qua., 18 de mar. de 2020 às 15:33, Rogério Ribeiro da Cruz <
notifications@github.com> escreveu:
