### ISSUE TITLE
Função para desabilitar conexões não está funcionando

### ISSUE THREAD

**Issue by raulvictorrosa** [totvs/tds-monitor-frontend#8]
Na versão 0.2.1 não estava funcionando a opção para desabilitar novas conexão, atualizei para a versão 0.2.11 e a função continua não funcionando, outro problema que começou a acontecer com está versão é a tela ficar piscando a cada atualização  Função para desabilitar novas conexões não está funcionando e a tela a cada intercalo de atualização.
![image](https://user-images.githubusercontent.com/13530065/98839201-07032000-2424-11eb-91bc-5cae870f1ac2.png)

**Comment by danielbolognani** [comment]
Boa tarde, primeiramente desculpe pela demora na resposta.
Temos uma nova versão disponível 0.2.13, consegue confirmar se com essa o problema está resolvido?

**Comment by raulvictorrosa** [comment]
@cgrossl00, @RobsonJP
